### ISSUE TITLE
Installation steps fail on self-hosted windows machines

### ISSUE THREAD

**Issue by steve-todorov** [AnimMouse/tool-cache#3]
Hey,

This action fails on self-hosted agents, because in your windows ps script you assume the environment is always "clean".
Unfortunately this is not true when you have self-hosted runners which are not disposable. In those cases your installation script will fail with the following:

```
Installing Rclone to tool cache
  
        Directory: C:\actions-runner\_work\_tool
    
  Mode                 LastWriteTime         Length Name                                                                 
  ----                 -------------         ------ ----                                                                 
  d-----         3/23/2023  11:35 AM                Rclone                                                               
  Move-Item : Cannot create a file when that file already exists.
  At C:\actions-runner\_work\_actions\AnimMouse\tool-cache\v1\scripts\install\Windows.ps1:5 char:1
  + Move-Item $env:RUNNER_TEMP\$env:folder_name\* $env:RUNNER_TOOL_CACHE\ ...
  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : WriteError: (C:\actions-runn...lone\rclone.exe:FileInfo) [Move-Item], IOException
      + FullyQualifiedErrorId : MoveFileInfoItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
```

And then in AnimMouse/setup-rclone:

```
Installing Rclone to tool cache

Run & $env:GITHUB_ACTION_PATH\scripts\add-to-path\Windows.ps1
Adding Rclone tool cache folder to path
Run & $env:GITHUB_ACTION_PATH\scripts\sign-in\Windows.ps1
Signing in to Rclone using Rclone config
  New-Item : An item with the specified name C:\Users\ADF VM\AppData\Roaming\rclone already exists.
  At C:\actions-runner\_work\_actions\steve-todorov\setup-rclone\issues\3\scripts\sign-in\Windows.ps1:4 char:1
  + New-Item $env:APPDATA\rclone -ItemType Directory
  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ResourceExists: (C:\Users\ADF VM\AppData\Roaming\rclone:String) [New-Item], IOException
      + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.NewItemCommand
```

The way to fix it is by `removing` the target directory so that it will always be "clean" or by forcing the creation of folders (in the case of the `sign-in` script)

**Comment by AnimMouse** [comment]
> This action fails on self-hosted agents, because in your windows ps script you assume the environment is always "clean".

I'm not expecting that my actions will be used in self-hosted runners, but I'm happy that you did.

> The way to fix it is by removing the target directory so that it will always be "clean" or by forcing the creation of folders (in the case of the sign-in script)

Forcing Move-Item will be much better and simpler.

Thanks for your bug report and the fix!

**Comment by steve-todorov** [comment]
Awesome! Thanks for pointing out the `-force` argument. I forgot about that possibility. 
Will you be able to create a release including these changes any time soon? We're currently using a branch with the fixes but would like to switch to a tagged version when possible :)

**Comment by AnimMouse** [comment]
> Will you be able to create a release including these changes any time soon? We're currently using a branch with the fixes but would like to switch to a tagged version when possible :)

It is already released and tested.

**Comment by steve-todorov** [comment]
Awesome! Many thanks for the fast response! :)
